<a href="https://colab.research.google.com/github/ancestor9/mathematics-for-machine-learning/blob/main/Linear%20Algebra/Chapter_2_Basic_Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import sympy as sy # 기호 수학(Symbolic Mathematics) 라이브러리, 대수학(Algebra)
sy.init_printing()

In [2]:
np.set_printoptions(precision=3)
np.set_printoptions(suppress=True)

In [5]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all" # display multiple lines

In [3]:
def round_expr(expr, num_digits):
    '''
    SymPy 라이브러리를 사용할 때 수식 내에 포함된 모든 숫자(상수)를 특정 소수점 자리수로 반올림하기 위한 함수
    '''
    return expr.xreplace({n : round(n, num_digits) for n in expr.atoms(sy.Number)})

# <font face="gotham" color="purple"> Matrix Operations</font>

Matrix _addition_ operations are straightforward:
1. $A+ B= B+ A$
2. $(A+B)+ C=A+(B+C)$
3. $c(A+B)=cA+cB$
4. $(c+d)A=cA+c{D}$
5. $c(dA)=(cd)A$
6. $A+{0}=A$, where ${0}$ is the zero matrix
7. For any $A$, there exists an $- A$, such that $ A+(- A)=0$.

They are as obvious as it looks, so no proofs are provided. And the matrix _multiplication_ properties are:
1. $ A({BC})=({AB}) C$
2. $c({AB})=(cA)B=A(cB)$
3. $A(B+ C)={AB}+{AC}$
4. $(B+C)A={BA}+{CA}$

Note that we need to differentiate between two types of multiplication: _Hadamard multiplication_, denoted as $A \odot B$ (element-wise multiplication), and _matrix multiplication_, denoted simply as $AB$.

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
A
B

array([[1, 2],
       [3, 4]])

array([[5, 6],
       [7, 8]])

In [ ]:
# Broadcasting
A+10
A-10
A*10
A/10

array([[11, 12],
       [13, 14]])

array([[-9, -8],
       [-7, -6]])

array([[10, 20],
       [30, 40]])

array([[0.1, 0.2],
       [0.3, 0.4]])

In [ ]:
A+B
A-B
A/B

array([[ 6,  8],
       [10, 12]])

array([[-4, -4],
       [-4, -4]])

array([[0.2  , 0.333],
       [0.429, 0.5  ]])

In [ ]:
A*B # this is Hadamard elementwise product

array([[ 5, 12],
       [21, 32]])

### **행렬과 벡터의 내적(Inner Product) 계산**

In [ ]:
a, b, c, d, e, f, g, h = sy.symbols('a, b, c, d, e, f, g, h', real = True)
A = sy.Matrix([[a, b], [c, d,]])
B = sy.Matrix([[e, f], [g, h,]])
A
print('\n')
B

⎡a  b⎤
⎢    ⎥
⎣c  d⎦

⎡e  f⎤
⎢    ⎥
⎣g  h⎦

In [ ]:
print('\n')
A+B
print('\n')
A-B
print('\n')
A*B   # 내적
print('\n')
A@B
print('\n')
np.dot(A,B)

⎡a + e  b + f⎤
⎢            ⎥
⎣c + g  d + h⎦

⎡a - e  b - f⎤
⎢            ⎥
⎣c - g  d - h⎦

⎡a⋅e + b⋅g  a⋅f + b⋅h⎤
⎢                    ⎥
⎣c⋅e + d⋅g  c⋅f + d⋅h⎦

⎡a⋅e + b⋅g  a⋅f + b⋅h⎤
⎢                    ⎥
⎣c⋅e + d⋅g  c⋅f + d⋅h⎦

array([[a*e + b*g, a*f + b*h],
       [c*e + d*g, c*f + d*h]], dtype=object)

In [ ]:
A@B # this is matrix product

⎡a⋅e + b⋅g  a⋅f + b⋅h⎤
⎢                    ⎥
⎣c⋅e + d⋅g  c⋅f + d⋅h⎦

Let's show explicitly the matrix multiplication rule for each element:

In [ ]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
A[0,:]
B[:,0]
np.sum(A[0,:]*B[:,0]) # element at (1, 1)

array([1, 2])

array([5, 7])

np.int64(19)

In [ ]:
np.sum(A[0,:]*B[:,0]) # element at (1, 1)
np.sum(A[1,:]*B[:,0]) # element at (2, 1)
np.sum(A[0,:]*B[:,1]) # element at (1, 2)
np.sum(A[1,:]*B[:,1]) # element at (2, 2)

np.int64(19)

np.int64(43)

np.int64(22)

np.int64(50)

## <font face="gotham" color="purple"> SymPy Demonstration: Addition </font>

Let's define all the letters as symbols in case we need to use them repeatedly. With this library, we can perform computations analytically, making it a valuable tool for learning linear algebra.

In [8]:
a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z = sy.symbols('a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z', real = True)

In [ ]:
A = sy.Matrix([[a, b, c], [d, e, f]])
A + A
A - A

⎡2⋅a  2⋅b  2⋅c⎤
⎢             ⎥
⎣2⋅d  2⋅e  2⋅f⎦

⎡0  0  0⎤
⎢       ⎥
⎣0  0  0⎦

In [ ]:
B = sy.Matrix([[g, h, i], [j, k, l]])
A + B
A - B

⎡a + g  b + h  c + i⎤
⎢                   ⎥
⎣d + j  e + k  f + l⎦

⎡a - g  b - h  c - i⎤
⎢                   ⎥
⎣d - j  e - k  f - l⎦

## <font face="gotham" color="purple"> SymPy Demonstration: Multiplication </font>

The matrix multiplication rules can be clearly understood by using symbols.

In [ ]:
A = sy.Matrix([[a, b, c], [d, e, f]])
B = sy.Matrix([[g, h, i], [j, k, l], [m, n, o]])
A
B

⎡a  b  c⎤
⎢       ⎥
⎣d  e  f⎦

⎡g  h  i⎤
⎢       ⎥
⎢j  k  l⎥
⎢       ⎥
⎣m  n  o⎦

In [ ]:
AB = A*B; AB

⎡a⋅g + b⋅j + c⋅m  a⋅h + b⋅k + c⋅n  a⋅i + b⋅l + c⋅o⎤
⎢                                                 ⎥
⎣d⋅g + e⋅j + f⋅m  d⋅h + e⋅k + f⋅n  d⋅i + e⋅l + f⋅o⎦

## <font face="gotham" color="purple"> Commutability </font>

Matrix multiplication usually does not commute, meaning ${AB} \neq {BA}$. For instance, consider matrices $A$ and $B$:

In [ ]:
A = sy.Matrix([[3, 4], [7, 8]])
B = sy.Matrix([[5, 3], [2, 1]])
A*B

⎡23  13⎤
⎢      ⎥
⎣51  29⎦

In [ ]:
B*A

⎡36  44⎤
⎢      ⎥
⎣13  16⎦

How do we find a commutable matrix? Let's try find out analytically

In [ ]:
A = sy.Matrix([[a, b], [c, d]])
B = sy.Matrix([[e, f], [g, h]])
A*B
B*A

⎡a⋅e + b⋅g  a⋅f + b⋅h⎤
⎢                    ⎥
⎣c⋅e + d⋅g  c⋅f + d⋅h⎦

⎡a⋅e + c⋅f  b⋅e + d⋅f⎤
⎢                    ⎥
⎣a⋅g + c⋅h  b⋅g + d⋅h⎦

# <font face="gotham" color="purple"> Transpose of Matrices </font>

Matrix $A_{n\times m}$ and its transpose is

In [6]:
A = sy.Matrix([[1, 2, 3], [4, 5, 6]]); A
A.transpose()

⎡1  2  3⎤
⎢       ⎥
⎣4  5  6⎦

⎡1  4⎤
⎢    ⎥
⎢2  5⎥
⎢    ⎥
⎣3  6⎦

The properties of transpose are
1. $(A^T)^T$
2. $(A+B)^T=A^T+B^T$
3. $(cA)^T=cA^T$
4. $(AB)^T=B^TA^T$

We can show why the last property holds with SymPy, define $A$ and $B$, multiply them, then transpose, that means $(AB)^T$

In [10]:
A = sy.Matrix([[a, b], [c, d], [e, f]])
B = sy.Matrix([[g, h, i], [j, k, l]])
AB = A*B
AB
AB_t = AB.transpose(); AB_t

⎡a⋅g + b⋅j  a⋅h + b⋅k  a⋅i + b⋅l⎤
⎢                               ⎥
⎢c⋅g + d⋅j  c⋅h + d⋅k  c⋅i + d⋅l⎥
⎢                               ⎥
⎣e⋅g + f⋅j  e⋅h + f⋅k  e⋅i + f⋅l⎦

⎡a⋅g + b⋅j  c⋅g + d⋅j  e⋅g + f⋅j⎤
⎢                               ⎥
⎢a⋅h + b⋅k  c⋅h + d⋅k  e⋅h + f⋅k⎥
⎢                               ⎥
⎣a⋅i + b⋅l  c⋅i + d⋅l  e⋅i + f⋅l⎦

Transpose $A$ and $B$, then multiply, meaning $B^TA^T$

In [11]:
B_t_A_t = B.transpose()*A.transpose()
B_t_A_t

⎡a⋅g + b⋅j  c⋅g + d⋅j  e⋅g + f⋅j⎤
⎢                               ⎥
⎢a⋅h + b⋅k  c⋅h + d⋅k  e⋅h + f⋅k⎥
⎢                               ⎥
⎣a⋅i + b⋅l  c⋅i + d⋅l  e⋅i + f⋅l⎦

Check if they are equal

In [ ]:
AB_t == B_t_A_t

True

# <font face="gotham" color="purple"> Identity Matrices </font>

This is an identity matrix $I_5$, only $1$'s on principal diagonal, all rest elements are $0$'s.

In [12]:
sy.eye(5)

⎡1  0  0  0  0⎤
⎢             ⎥
⎢0  1  0  0  0⎥
⎢             ⎥
⎢0  0  1  0  0⎥
⎢             ⎥
⎢0  0  0  1  0⎥
⎢             ⎥
⎣0  0  0  0  1⎦

Identity matrix properties:

$$
AI=IA = A
$$

Let's generate $ I$ and $ A$ and show if it holds

In [13]:
I = np.eye(5); I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
A = np.around(np.random.rand(5, 5)*100); A # generate a random matrix

array([[65.,  5., 65., 97., 61.],
       [41., 97., 41., 82., 89.],
       [66.,  5., 39., 72., 58.],
       [46., 48., 50., 14., 32.],
       [19., 79., 35., 15., 83.]])

Check if they are equal

In [16]:
A@I

array([[65.,  5., 65., 97., 61.],
       [41., 97., 41., 82., 89.],
       [66.,  5., 39., 72., 58.],
       [46., 48., 50., 14., 32.],
       [19., 79., 35., 15., 83.]])

In [17]:
I@A

array([[65.,  5., 65., 97., 61.],
       [41., 97., 41., 82., 89.],
       [66.,  5., 39., 72., 58.],
       [46., 48., 50., 14., 32.],
       [19., 79., 35., 15., 83.]])

In [15]:
(A@I == I@A).all()

np.True_

# <font face="gotham" color="purple"> Elementary Matrix </font>

An _elementary matrix_ is a matrix that can be obtained from a single elementary row operation on an identity matrix. Such as:

$$
\left[
\begin{array}{ccc}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{array}
\right]
\begin{array}{c}
R_1 \leftrightarrow R_2 \\
~ \\
~
\end{array}
\qquad \Longrightarrow \qquad
\left[
\begin{array}{ccc}
0 & 1 & 0 \\
1 & 0 & 0 \\
0 & 0 & 1
\end{array}
\right]
$$

Where $R_1 \leftrightarrow R_2$ means exchanging row 1 and row 2, we denote the transformed matrix as $E$. Then, left multiply $E$ onto a matrix $A$ will perform the exact the same row operation.

First, generate matrix $A$.

In [19]:
A = sy.randMatrix(3, percent = 80); A # generate a random matrix with 80% of entries being nonzero

⎡17  11  6 ⎤
⎢          ⎥
⎢20  32  0 ⎥
⎢          ⎥
⎣0   30  49⎦

Create an elementary matrix with $R_1\leftrightarrow R_2$

In [20]:
E = sy.Matrix([[0, 1, 0], [1, 0, 0], [0, 0, 1]]);E

⎡0  1  0⎤
⎢       ⎥
⎢1  0  0⎥
⎢       ⎥
⎣0  0  1⎦

Notice that by left-multiplying $E$ onto $A$, matrix $A$ also switches rows 1 and 2.

In [21]:
E*A

⎡20  32  0 ⎤
⎢          ⎥
⎢17  11  6 ⎥
⎢          ⎥
⎣0   30  49⎦

In the next section, we will refresh an important conclusion: an _invertible matrix_ is a product of a series of elementary matrices.

# <font face="gotham" color="purple"> Inverse Matrices </font>

If ${AB}={BA}=\mathbf{I}$, $ B$ is called the inverse of matrix $  A$, denoted as $ B=  A^{-1}$.


NumPy has convenient function ```np.linalg.inv()``` for computing inverse matrices. Generate $ A$

In [24]:
A = np.round(10*np.random.randn(5,5)); A

array([[  2., -12.,  -8.,  -1.,  16.],
       [-12.,  -0., -21.,  -9.,   1.],
       [  3.,  11.,   3.,   7.,  -2.],
       [ -6.,  10.,  32.,  13.,  -6.],
       [-10., -11., -14., -10.,   1.]])

In [25]:
Ainv = np.linalg.inv(A); Ainv

array([[-0.016, -0.021, -0.044, -0.042, -0.065],
       [-0.011,  0.142, -0.15 ,  0.007, -0.222],
       [-0.007,  0.058, -0.163,  0.024, -0.134],
       [ 0.043, -0.203,  0.421,  0.003,  0.377],
       [ 0.056,  0.125, -0.162,  0.023, -0.202]])

Verify if they are truly inverse of each other

In [26]:
A@Ainv

array([[ 1.,  0.,  0.,  0.,  0.],
       [-0.,  1.,  0., -0., -0.],
       [ 0.,  0.,  1.,  0., -0.],
       [ 0.,  0.,  0.,  1., -0.],
       [-0.,  0., -0., -0.,  1.]])

The ```-0.``` means there are more digits after point, but omitted here.

## <font face="gotham" color="purple"> Properties of Inverse Matrices </font>

1. If $A$ and $B$ are both invertible, then $(AB)^{-1}=B^{-1}A^{-1}$.
2. If $A$ is invertible, then $(A^T)^{-1}=(A^{-1})^T$.
3. If $A$ and $B$ are both invertible and symmetric such that $AB=BA$, then $A^{-1}B$ is symmetric.

The _first property_ is straightforward
$$
\begin{align}
ABB^{-1}A^{-1}=AIA^{-1}=I=AB(AB)^{-1}
\end{align}
$$

The trick of _second property_ is to show that
$$
A^T(A^{-1})^T = I
$$
We can use the property of transpose
$$
A^T(A^{-1})^T=(A^{-1}A)^T = I^T = I
$$

The _third property_ is to show
$$
A^{-1}B = (A^{-1}B)^T
$$
Again use the property of transpose
$$
(A^{-1}B)^{T}=B^T(A^{-1})^T=B(A^T)^{-1}=BA^{-1}
$$
We use the $AB = BA$ condition to proceed
\begin{align*}
AB&=BA\\
A^{-1}ABA^{-1}&=A^{-1}BAA^{-1}\\
BA^{-1}&=A^{-1}B
\end{align*}
The plug in the previous equation, we have
$$
(A^{-1}B)^{T}=BA^{-1}=A^{-1}B
$$