In [9]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
# scalar, vector, matrix, tensor
import torch
# torch.empty(size): uninitiallized
x = torch.empty(1) # scalar
print(x)

tensor([2.1176e-19])


In [5]:
x = torch.empty(3) # vector, 1D
print(x)
x = torch.empty(2,3) # matrix, 2D
print(x)
x = torch.empty(2,2,3) # tensor, 3 dimensions
print(x)
x = torch.empty(2,2,2,3) # tensor, 4 dimensions
print(x)

tensor([2.1175e-19, 4.3271e-41, 2.1175e-19])
tensor([[4.7961e-32, 0.0000e+00, 5.0137e-35],
        [0.0000e+00, 1.1210e-43, 0.0000e+00]])
tensor([[[4.9503e-35, 0.0000e+00, 2.3743e-32],
         [0.0000e+00, 1.4013e-45, 0.0000e+00]],

        [[4.5447e+30, 7.0062e+22, 2.1707e-18],
         [1.9284e+31, 3.2314e-18, 1.5099e-07]]])
tensor([[[[0.0000e+00, 0.0000e+00, 2.3747e-32],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]]],


        [[[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 1.4013e-45],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]]]])


In [6]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print(x)

# torch.zeros(size), fill with 0
# torch.ones(size), fill with 1
x = torch.zeros(5, 3)
print(x)

# check size
print(x.size())

# check data type
print(x.dtype)

tensor([[0.3672, 0.9396, 0.9217],
        [0.4497, 0.3768, 0.2375],
        [0.0880, 0.9314, 0.1362],
        [0.7726, 0.4934, 0.0673],
        [0.8709, 0.4647, 0.1418]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([5, 3])
torch.float32


In [7]:
# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.float16)
print(x)

# check type
print(x.dtype)

# construct from data
x = torch.tensor([5.5, 3])
print(x.size())

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
torch.float16
torch.Size([2])


In [10]:
# requires_grad argument
# This will tell pytorch that it will need to calculate the gradients for this tensor
# later in your optimization steps
# i.e. this is a variable in your model that you want to optimize
x = torch.tensor([5.5, 3], requires_grad=True)

# Operations
y = torch.rand(2, 2)
x = torch.rand(2, 2)

# elementwise addition
z = x + y

torch.add(x,y)

z

tensor([[0.9409, 0.7940],
        [0.8775, 1.4084]])

tensor([[0.9409, 0.7940],
        [0.8775, 1.4084]])

In [11]:
# in place addition, everythin with a trailing underscore is an inplace operation
# i.e. it will modify the variable
y.add_(x)

tensor([[0.9409, 0.7940],
        [0.8775, 1.4084]])

In [12]:
# substraction
z = x - y
z = torch.sub(x, y)

# multiplication
z = x * y
z = torch.mul(x,y)

# division
z = x / y
z = torch.div(x,y)

# Slicing
x = torch.rand(5,3)
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

# Get the actual value if only 1 element in your tensor
print(x[1,1].item())

tensor([[0.2855, 0.8641, 0.6526],
        [0.1448, 0.8065, 0.4086],
        [0.1942, 0.3776, 0.6280],
        [0.6942, 0.2063, 0.5453],
        [0.2524, 0.2710, 0.8106]])
tensor([0.2855, 0.1448, 0.1942, 0.6942, 0.2524])
tensor([0.1448, 0.8065, 0.4086])
tensor(0.8065)
0.8064810037612915


In [13]:
# Reshape with torch.view()
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
# if -1 it pytorch will automatically determine the necessary size
print(x.size(), y.size(), z.size())

# Numpy
# Converting a Torch Tensor to a NumPy array and vice versa is very easy
a = torch.ones(5)
print(a)

# torch to numpy with .numpy()
b = a.numpy()
print(b)
print(type(b))

# Carful: If the Tensor is on the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other
a.add_(1)
print(a)
print(b)


torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


tensor([2., 2., 2., 2., 2.])

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [14]:

# numpy to torch with .from_numpy(x)
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

# again be careful when modifying
a += 1
print(a)
print(b)

# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available )
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    z.to("cpu")       # ``.to`` can also change dtype together!
    # z = z.numpy()

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
