# Solving Linear Systems: 3 variables

In this lab, you will keep developing your skills using Python to solve systems of linear equations. In this notebook you will:

- Use `NumPy` linear algebra package to find the solutions to the system of linear equations
- Perform row reduction to bring matrix into row echelon form
- Find the solution for the system of linear equations using row reduced matrix
- Evaluate the determinant of the matrix to see again the connection between matrix singularity and the number of solutions of the linear system

# Table of Contents
- [ 1 - Representing and Solving a System of Linear Equations using Matrices](#1)
  - [ 1.1 - System of Linear Equations](#1.1)
  - [ 1.2 - Solving Systems of Linear Equations using Matrices](#1.2)
  - [ 1.3 - Evaluating the Determinant of a Matrix](#1.3)

## Packages

Load the `NumPy` package to access its functions.

In [ ]:
import numpy as np

<a name='1'></a>
## 1 - Representing and Solving a System of Linear Equations using Matrices

<a name='1.1'></a>
### 1.1 - System of Linear Equations

Here is a **system of linear equations** (or **linear system**) with three equations and three unknown variables:


$$\begin{cases}
4x_1-3x_2+x_3=-10, \\ 2x_1+x_2+3x_3=0, \\ -x_1+2x_2-5x_3=17, \end{cases}\tag{1}$$

**To solve** this system of linear equations means to find such values of the variables $x_1$, $x_2$, $x_3$, that all of its equations are simultaneously satisfied.

<a name='1.2'></a>
### 1.2 - Solving Systems of Linear Equations using Matrices

Let's prepare to solve the linear system $(1)$ using `NumPy`. $A$ will be a matrix, each row will represent one equation in the system and each column will correspond to the variable $x_1$, $x_2$, $x_3$. And $b$ is a 1-D array of the free (right side) coefficients:

In [ ]:
A = np.array([
        [4, -3, 1],
        [2, 1, 3],
        [-1, 2, -5]
    ], dtype=np.dtype(float))

b = np.array([-10, 0, 17], dtype=np.dtype(float))

print("Matrix A:")
print(A)
print("\nArray b:")
print(b)

Matrix A:
[[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]

Array b:
[-10.   0.  17.]


Check the dimensions of $A$ and $b$ using `shape()` function:

In [ ]:
print(f"Shape of A: {np.shape(A)}")
print(f"Shape of b: {np.shape(b)}")

Shape of A: (3, 3)
Shape of b: (3,)


Now use `np.linalg.solve(A, b)` function to find the solution of the system $(1)$. The result will be saved in the 1-D array $x$. The elements will correspond to the values of $x_1$, $x_2$ and $x_3$:

In [ ]:
x = np.linalg.solve(A, b)

print(f"Solution: {x}")

Solution: [ 1.  4. -2.]


Try to substitute those values of $x_1$, $x_2$ and $x_3$ into the original system of equations to check its consistency.

<a name='1.3'></a>
### 1.3 - Evaluating the Determinant of a Matrix

Matrix $A$ corresponding to the linear system $(1)$ is a **square matrix** - it has the same number of rows and columns. In the case of a square matrix it is possible to calculate its determinant - a real number that characterizes some properties of the matrix. A linear system containing three equations with three unknown variables will have one solution if and only if the matrix $A$ has a non-zero determinant.

Let's calculate the determinant using `np.linalg.det(A)` function:

In [ ]:
d = np.linalg.det(A)

print(f"Determinant of matrix A: {d:.2f}")

Determinant of matrix A: -60.00


## **행렬공식(Matrix Formulation)**
행렬의 역행렬($A^{-1}$)을 이용하여 연립방정식의 해를 구하는 원리와 NumPy 코드를 정리
- 행렬 형태로 나타내면 $Ax = B$
- $A$는 계수 행렬
- $x$는 우리가 구하려는 해 $[x_1, x_2, x_3]$
- $B$는 결과값 $[-10, 0, 17]$
> 양변의 왼쪽에 역행렬 $A^{-1}$을 곱하면 다음과 같이 해를 구함:

$$A^{-1} \cdot A \cdot x = A^{-1} \cdot B$$$$I \cdot x = A^{-1} \cdot B$$$$x = A^{-1} \cdot B$$

- start

In [1]:
import numpy as np

# 1. 계수 행렬 A 정의
A = np.array([
    [4, -3, 1],
    [2, 1, 3],
    [-1, 2, -5]
])

# 2. 결과 상수 벡터 B 정의
B = np.array([-10, 0, 17])

# 3. A의 역행렬(A_inv) 구하기
A_inv = np.linalg.inv(A)

# 4. 해(x) 구하기: A_inv와 B의 행렬 곱 (dot product)
# x = A^-1 * B
x = np.dot(A_inv, B)

print("--- 계수 행렬 A ---")
print(A)

print("\n--- A의 역행렬 (A^-1) ---")
print(A_inv)

print("\n--- 최종 해 [x1, x2, x3] ---")
print(x)

--- 계수 행렬 A ---
[[ 4 -3  1]
 [ 2  1  3]
 [-1  2 -5]]

--- A의 역행렬 (A^-1) ---
[[ 0.18333333  0.21666667  0.16666667]
 [-0.11666667  0.31666667  0.16666667]
 [-0.08333333  0.08333333 -0.16666667]]

--- 최종 해 [x1, x2, x3] ---
[ 1.  4. -2.]


- end